/*void tree1w(){

   // create a tree file tree1.root - create the file, the Tree and
   // a few branches

   TFile f("tree1.root","recreate");
   TTree t1("t1","a simple Tree with simple variables");
   Float_t px, py, pz;
   Double_t random;
   Int_t ev;
   t1.Branch("px",&px,"px/F");
   t1.Branch("py",&py,"py/F");
   t1.Branch("pz",&pz,"pz/F");
   t1.Branch("ev",&ev,"ev/I");

   // fill the tree
   for (Int_t i=0; i<10000; i++) {
      gRandom->Rannor(px,py);
      pz = px*px + py*py;
      random = gRandom->Rndm();
      ev = i;
      t1.Fill();
   }

   // save the Tree heade; the file will be automatically closed
   // when going out of the function scope
   t1.Write();
}*/

void tree1r(const char* filename = "tree1.root"){

   // read the Tree generated by tree1w and fill two histograms
   // note that we use "new" to create the TFile and TTree objects,
   // to keep them alive after leaving this function.

   TFile *f = new TFile(filename);
   TTree *t1 = (TTree*)f->Get("t1");
   Double_t px, py, pz;
   Double_t random;
   Int_t EventID;
   t1->SetBranchAddress("px",&px);
   t1->SetBranchAddress("py",&py);
   t1->SetBranchAddress("pz",&pz);
   t1->SetBranchAddress("random",&random);
   t1->SetBranchAddress("EventID",&EventID);

   // create two histograms
   TH1D *hpx   = new TH1D("hpx","px distribution",1000,-100,100);
   TH2D *hpxpy = new TH2D("hpxpy","py vs px",1000,-100,100,1000,-100,100);
   TH2D *hpypz = new TH2D("hpypz","pz vs py",1000,-100,100,1000,-100,100);
   TH2D *hpxpz = new TH2D("hpxpz","pz vs px",1000,-100,100,1000,-100,100);

   //read all entries and fill the histogramsi
   Int_t nentries = (Int_t)t1->GetEntries();
   for (Int_t i=0; i<nentries; i++) {
      t1->GetEntry(i);
      hpx->Fill(px);
      hpxpy->Fill(px,py);
      hpypz->Fill(py,pz);
      hpxpz->Fill(px,pz);
   }

//  t1->Write();

  if (gROOT->IsBatch()) return;
  new TBrowser ();
  t1->StartViewer();

}







